cvEn: aguiter-cv-en.pdf
cvEs: aguiter-cv-es.pdf
name: Alejandro Guiter
role: Software Engineer
photo: me.jpg
photoAlt: Alejandro Guiter
yearsExperience: 5
specialty: Next.js, React & TypeScript
locationCity: Madrid
email: aleguiter9@gmail.com
githubUrl: https://github.com/aleguiter09
linkedinUrl: https://www.linkedin.com/in/alejandroguiter
