export const experiences = [
  {
    id: 1,
    src: "/images/izertis.jpg",
    alt: "izertis-logo",
    position: "Frontend Developer",
    company: "Izertis",
    date: "Oct 2023 - Present",
    time: "Present",
    country: "Madrid, Spain",
    description:
      "Currently working as a Frontend Developer developing and maintaining multiple web applications for a client in the fashion industry.",
    stack: ["react", "next", "ts", "sass"],
  },
  {
    id: 2,
    src: "/images/folderit.jpg",
    alt: "folderit-logo",
    position: "Full Stack Developer",
    company: "Folder IT",
    date: "Sep 2021 - Sep 2023",
    time: "2 years",
    country: "Santa Fe, Argentina",
    description:
      "Developed and enhanced both soft and technical skills across diverse projects and technologies. Worked for clients in the agriculture industry, e-commerce and finances.",
    stack: [
      "react",
      "react-native",
      "next",
      "ts",
      "sass",
      "mongo",
      "nest",
      "vue",
    ],
  },
  {
    id: 3,
    src: "/images/serfe.png",
    alt: "serfe-logo",
    position: "Full Stack Developer",
    company: "Serfe",
    date: "Apr 2021 - Sep 2021",
    time: "6 months",
    country: "Santa Fe, Argentina",
    description:
      "Development, testing and maintenance of web applications. Worked on several amount of projects from start to finish both alone and in with colleagues of the company.",
    stack: ["react", "js", "python", "sass", "wordpress"],
  },
  {
    id: 4,
    src: "/images/utn.png",
    alt: "utn-logo",
    position: "Intern I+D",
    company: "Universidad Tecnológica Nacional",
    date: "Jul 2020 - Dec 2020",
    time: "6 months",
    country: "Santa Fe, Argentina",
    description:
      "Application of AI techniques to the design and analysis of business processes. In charge of the investigation and development of the project.",
    stack: ["python", "spacy", "research"],
  },
];
