export const experiences = [
  {
    id: 5,
    src: "/images/ciklum.jpg",
    alt: "ciklum-logo",
    position: "Frontend Engineer",
    company: "Ciklum",
    date: "ciklum.date",
    country: "ciklum.country",
    description: ["ciklum.description", "ciklum.description2"],
    stack: ["react", "next", "ts", "tailwind"],
  },
  {
    id: 1,
    src: "/images/izertis.jpg",
    alt: "izertis-logo",
    position: "Frontend Developer",
    company: "Izertis",
    date: "izertis.date",
    country: "izertis.country",
    description: ["izertis.description", "izertis.description2"],
    stack: ["react", "next", "ts", "sass"],
  },
  {
    id: 2,
    src: "/images/folderit.jpg",
    alt: "folderit-logo",
    position: "Full Stack Developer",
    company: "Folder IT",
    date: "folder.date",
    country: "folder.country",
    description: ["folder.description", "folder.description2"],
    stack: ["react", "react-native", "next", "ts", "mongo", "nest"],
  },
  {
    id: 3,
    src: "/images/serfe.png",
    alt: "serfe-logo",
    position: "Full Stack Developer",
    company: "Serfe",
    date: "serfe.date",
    country: "serfe.country",
    description: ["serfe.description", "serfe.description2"],
    stack: ["react", "js", "python", "sass", "wordpress"],
  },
  {
    id: 4,
    src: "/images/utn.png",
    alt: "utn-logo",
    position: "Intern R+D",
    company: "Universidad Tecnológica Nacional",
    date: "utn.date",
    country: "utn.country",
    description: ["utn.description", "utn.description2"],
    stack: ["python", "spacy", "research"],
  },
];
